export const MOCK = {
  bg: 'var(--bg-primary)',
  bgCard: 'var(--bg-card)',
  bgMuted: 'var(--bg-tertiary)',
  border: 'var(--border)',
  borderSubtle: 'var(--border)',
  foreground: 'var(--text-primary)',
  foregroundMuted: 'var(--text-secondary)',
  foregroundFaint: 'var(--text-muted)',
  primary: '#2563eb',
  primaryLight: '#3b82f6',
  primaryForeground: '#ffffff',
  gradientFrom: '#2563eb',
  gradientTo: '#6366f1',
  success: '#16a34a',
  successBg: 'rgba(22, 163, 74, 0.12)',
  warning: '#ca8a04',
  warningBg: 'rgba(202, 138, 4, 0.12)',
  destructive: '#dc2626',
  destructiveBg: 'rgba(220, 38, 38, 0.12)',
} as const
